name: ModNVote
version: "${version}"
main: com.modnmetl.modnvote.ModNVotePlugin
api-version: "1.21"
author: MODN METL LTD
website: https://modnmetl.com

commands:
  modnvote:
    description: ModNVote main command
    usage: "/modnvote <yes|no|status|verify|reset|reload|audit|fullaudit>"
    permission: modnvote.use

permissions:
  modnvote.*:
    description: All ModNVote permissions
    default: op
    children:
      modnvote.use: true
      modnvote.vote: true
      modnvote.status: true
      modnvote.verify: true
      modnvote.admin.reset: true
      modnvote.admin.reload: true
      modnvote.admin.audit: true
      modnvote.admin.fullaudit: true

  modnvote.use:
    description: Allow using /modnvote
    default: true

  modnvote.vote:
    description: Allow casting a vote
    default: true

  modnvote.status:
    description: Allow viewing status
    default: true

  modnvote.verify:
    description: Allow verifying tally integrity
    default: true

  modnvote.admin.reset:
    description: Reset all votes and tallies
    default: op

  modnvote.admin.reload:
    description: Reload plugin configuration
    default: op

  modnvote.admin.audit:
    description: Show audit summary
    default: op

  modnvote.admin.fullaudit:
    description: Full audit (grouped by IP)
    default: op
